# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: au.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import world_amazon_pb2 as world__amazon__pb2
import world_ups_pb2 as world__ups__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='au.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x08\x61u.proto\x1a\x12world_amazon.proto\x1a\x0fworld_ups.proto\"1\n\rUASendWorldId\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x0f\n\x06seqnum\x18\xff\x01 \x02(\x03\".\n\x0c\x41UQueryUpsid\x12\r\n\x05upsid\x18\x01 \x02(\x03\x12\x0f\n\x06seqnum\x18\xff\x01 \x02(\x03\"-\n\tWarehouse\x12\n\n\x02id\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\"\x7f\n\x0f\x41URequestPickup\x12\x19\n\x06things\x18\x01 \x03(\x0b\x32\t.AProduct\x12\x1c\n\x08wareinfo\x18\x02 \x02(\x0b\x32\n.Warehouse\x12\x13\n\x0btrackingnum\x18\x03 \x02(\x03\x12\r\n\x05upsid\x18\x04 \x01(\x03\x12\x0f\n\x06seqnum\x18\xff\x01 \x02(\x03\"B\n\tUAArrived\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x13\n\x0btrackingnum\x18\x02 \x02(\x03\x12\x0f\n\x06seqnum\x18\xff\x01 \x02(\x03\"d\n\nAULoadOver\x12\x13\n\x0btrackingnum\x18\x01 \x02(\x03\x12\x0f\n\x07truckid\x18\x02 \x02(\x05\x12\x1f\n\x03loc\x18\x03 \x02(\x0b\x32\x12.UDeliveryLocation\x12\x0f\n\x06seqnum\x18\xff\x01 \x02(\x03\"5\n\rUADeliverOver\x12\x13\n\x0btrackingnum\x18\x01 \x02(\x03\x12\x0f\n\x06seqnum\x18\xff\x01 \x02(\x03\"\xa6\x01\n\tAUCommand\x12 \n\x06pickup\x18\x01 \x03(\x0b\x32\x10.AURequestPickup\x12\x1f\n\npackloaded\x18\x02 \x03(\x0b\x32\x0b.AULoadOver\x12!\n\nqueryupsid\x18\x03 \x01(\x0b\x32\r.AUQueryUpsid\x12\x14\n\x06\x65rrors\x18\x04 \x03(\x0b\x32\x04.Err\x12\x0c\n\x04\x61\x63ks\x18\x05 \x03(\x03\x12\x0f\n\x06seqnum\x18\xff\x01 \x01(\x03\"\x91\x01\n\tUACommand\x12\x1e\n\x06sendid\x18\x01 \x01(\x0b\x32\x0e.UASendWorldId\x12\x1b\n\x07\x61rrived\x18\x02 \x03(\x0b\x32\n.UAArrived\x12#\n\x0b\x64\x65liverover\x18\x03 \x03(\x0b\x32\x0e.UADeliverOver\x12\x14\n\x06\x65rrors\x18\x04 \x03(\x0b\x32\x04.Err\x12\x0c\n\x04\x61\x63ks\x18\x05 \x03(\x03\"9\n\x03\x45rr\x12\x0b\n\x03\x65rr\x18\x01 \x02(\t\x12\x14\n\x0coriginseqnum\x18\x02 \x02(\x03\x12\x0f\n\x06seqnum\x18\xff\x01 \x02(\x03')
  ,
  dependencies=[world__amazon__pb2.DESCRIPTOR,world__ups__pb2.DESCRIPTOR,])




_UASENDWORLDID = _descriptor.Descriptor(
  name='UASendWorldId',
  full_name='UASendWorldId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='UASendWorldId.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UASendWorldId.seqnum', index=1,
      number=255, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=98,
)


_AUQUERYUPSID = _descriptor.Descriptor(
  name='AUQueryUpsid',
  full_name='AUQueryUpsid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upsid', full_name='AUQueryUpsid.upsid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AUQueryUpsid.seqnum', index=1,
      number=255, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=146,
)


_WAREHOUSE = _descriptor.Descriptor(
  name='Warehouse',
  full_name='Warehouse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Warehouse.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='Warehouse.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Warehouse.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=193,
)


_AUREQUESTPICKUP = _descriptor.Descriptor(
  name='AURequestPickup',
  full_name='AURequestPickup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='things', full_name='AURequestPickup.things', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wareinfo', full_name='AURequestPickup.wareinfo', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackingnum', full_name='AURequestPickup.trackingnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upsid', full_name='AURequestPickup.upsid', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AURequestPickup.seqnum', index=4,
      number=255, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=322,
)


_UAARRIVED = _descriptor.Descriptor(
  name='UAArrived',
  full_name='UAArrived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UAArrived.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackingnum', full_name='UAArrived.trackingnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UAArrived.seqnum', index=2,
      number=255, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=390,
)


_AULOADOVER = _descriptor.Descriptor(
  name='AULoadOver',
  full_name='AULoadOver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackingnum', full_name='AULoadOver.trackingnum', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truckid', full_name='AULoadOver.truckid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loc', full_name='AULoadOver.loc', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AULoadOver.seqnum', index=3,
      number=255, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=492,
)


_UADELIVEROVER = _descriptor.Descriptor(
  name='UADeliverOver',
  full_name='UADeliverOver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackingnum', full_name='UADeliverOver.trackingnum', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UADeliverOver.seqnum', index=1,
      number=255, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=547,
)


_AUCOMMAND = _descriptor.Descriptor(
  name='AUCommand',
  full_name='AUCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pickup', full_name='AUCommand.pickup', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packloaded', full_name='AUCommand.packloaded', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queryupsid', full_name='AUCommand.queryupsid', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='AUCommand.errors', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='AUCommand.acks', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AUCommand.seqnum', index=5,
      number=255, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=716,
)


_UACOMMAND = _descriptor.Descriptor(
  name='UACommand',
  full_name='UACommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sendid', full_name='UACommand.sendid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrived', full_name='UACommand.arrived', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deliverover', full_name='UACommand.deliverover', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='UACommand.errors', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='UACommand.acks', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=719,
  serialized_end=864,
)


_ERR = _descriptor.Descriptor(
  name='Err',
  full_name='Err',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='Err.err', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='originseqnum', full_name='Err.originseqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='Err.seqnum', index=2,
      number=255, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=866,
  serialized_end=923,
)

_AUREQUESTPICKUP.fields_by_name['things'].message_type = world__amazon__pb2._APRODUCT
_AUREQUESTPICKUP.fields_by_name['wareinfo'].message_type = _WAREHOUSE
_AULOADOVER.fields_by_name['loc'].message_type = world__ups__pb2._UDELIVERYLOCATION
_AUCOMMAND.fields_by_name['pickup'].message_type = _AUREQUESTPICKUP
_AUCOMMAND.fields_by_name['packloaded'].message_type = _AULOADOVER
_AUCOMMAND.fields_by_name['queryupsid'].message_type = _AUQUERYUPSID
_AUCOMMAND.fields_by_name['errors'].message_type = _ERR
_UACOMMAND.fields_by_name['sendid'].message_type = _UASENDWORLDID
_UACOMMAND.fields_by_name['arrived'].message_type = _UAARRIVED
_UACOMMAND.fields_by_name['deliverover'].message_type = _UADELIVEROVER
_UACOMMAND.fields_by_name['errors'].message_type = _ERR
DESCRIPTOR.message_types_by_name['UASendWorldId'] = _UASENDWORLDID
DESCRIPTOR.message_types_by_name['AUQueryUpsid'] = _AUQUERYUPSID
DESCRIPTOR.message_types_by_name['Warehouse'] = _WAREHOUSE
DESCRIPTOR.message_types_by_name['AURequestPickup'] = _AUREQUESTPICKUP
DESCRIPTOR.message_types_by_name['UAArrived'] = _UAARRIVED
DESCRIPTOR.message_types_by_name['AULoadOver'] = _AULOADOVER
DESCRIPTOR.message_types_by_name['UADeliverOver'] = _UADELIVEROVER
DESCRIPTOR.message_types_by_name['AUCommand'] = _AUCOMMAND
DESCRIPTOR.message_types_by_name['UACommand'] = _UACOMMAND
DESCRIPTOR.message_types_by_name['Err'] = _ERR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UASendWorldId = _reflection.GeneratedProtocolMessageType('UASendWorldId', (_message.Message,), dict(
  DESCRIPTOR = _UASENDWORLDID,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:UASendWorldId)
  ))
_sym_db.RegisterMessage(UASendWorldId)

AUQueryUpsid = _reflection.GeneratedProtocolMessageType('AUQueryUpsid', (_message.Message,), dict(
  DESCRIPTOR = _AUQUERYUPSID,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:AUQueryUpsid)
  ))
_sym_db.RegisterMessage(AUQueryUpsid)

Warehouse = _reflection.GeneratedProtocolMessageType('Warehouse', (_message.Message,), dict(
  DESCRIPTOR = _WAREHOUSE,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:Warehouse)
  ))
_sym_db.RegisterMessage(Warehouse)

AURequestPickup = _reflection.GeneratedProtocolMessageType('AURequestPickup', (_message.Message,), dict(
  DESCRIPTOR = _AUREQUESTPICKUP,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:AURequestPickup)
  ))
_sym_db.RegisterMessage(AURequestPickup)

UAArrived = _reflection.GeneratedProtocolMessageType('UAArrived', (_message.Message,), dict(
  DESCRIPTOR = _UAARRIVED,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:UAArrived)
  ))
_sym_db.RegisterMessage(UAArrived)

AULoadOver = _reflection.GeneratedProtocolMessageType('AULoadOver', (_message.Message,), dict(
  DESCRIPTOR = _AULOADOVER,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:AULoadOver)
  ))
_sym_db.RegisterMessage(AULoadOver)

UADeliverOver = _reflection.GeneratedProtocolMessageType('UADeliverOver', (_message.Message,), dict(
  DESCRIPTOR = _UADELIVEROVER,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:UADeliverOver)
  ))
_sym_db.RegisterMessage(UADeliverOver)

AUCommand = _reflection.GeneratedProtocolMessageType('AUCommand', (_message.Message,), dict(
  DESCRIPTOR = _AUCOMMAND,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:AUCommand)
  ))
_sym_db.RegisterMessage(AUCommand)

UACommand = _reflection.GeneratedProtocolMessageType('UACommand', (_message.Message,), dict(
  DESCRIPTOR = _UACOMMAND,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:UACommand)
  ))
_sym_db.RegisterMessage(UACommand)

Err = _reflection.GeneratedProtocolMessageType('Err', (_message.Message,), dict(
  DESCRIPTOR = _ERR,
  __module__ = 'au_pb2'
  # @@protoc_insertion_point(class_scope:Err)
  ))
_sym_db.RegisterMessage(Err)


# @@protoc_insertion_point(module_scope)
