# Generated by Django 4.0.1 on 2022-04-23 14:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_from', models.IntegerField()),
                ('message_from_name', models.TextField()),
                ('message_to', models.IntegerField(null=True)),
                ('message_to_name', models.TextField()),
                ('message', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageid', models.AutoField(primary_key=True, serialize=False)),
                ('trackingnum', models.BigIntegerField()),
                ('userid', models.IntegerField(null=True)),
                ('destinationx', models.IntegerField(null=True)),
                ('destinationy', models.IntegerField(null=True)),
                ('packagestatus', models.SmallIntegerField(choices=[(1, 'waiting for pickup'), (2, 'waiting for loading'), (3, 'deliverying'), (4, 'delivered')])),
                ('description', models.CharField(max_length=1000, null=True)),
                ('truckid', models.IntegerField(null=True)),
                ('warehouseid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('truckid', models.IntegerField(unique=True)),
                ('truckstatus', models.SmallIntegerField(choices=[(1, 'idle'), (2, 'travelling'), (3, 'arrived at warehouse'), (4, 'loading'), (5, 'delivering')])),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('warehousex', models.IntegerField()),
                ('warehousey', models.IntegerField()),
            ],
        ),
    ]
